name: reservandonos_challenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-262.0.dev <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_modular: ^5.0.3
  flutter_widget_from_html: ^0.10.5
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1
  overlay_support: ^2.1.0
  provider: ^6.0.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
